// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         since: "since"
 *     }
 */
export interface ChangesSinceRequest {
    /** Exact vault id or name from list_vaults. Required whenever the key can reach more than one vault; never guess or use one client's vault for another. */
    vault?: string;
    /** ISO 8601 datetime, e.g. 2026-07-18T00:00:00Z */
    since: string;
}
