// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         entityId: "entityId"
 *     }
 */
export interface ExpandGraphRequest {
    /** Exact vault id or name from list_vaults. Required whenever the key can reach more than one vault; never guess or use one client's vault for another. */
    vault?: string;
    /** Starting entity id */
    entityId: string;
    /** 1 or 2 (default 1) */
    depth?: number;
}
