// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         query: "query"
 *     }
 */
export interface FindEmailThreadRequest {
    /** Exact vault id or name from list_vaults. Required whenever the key can reach more than one vault; never guess or use one client's vault for another. */
    vault?: string;
    /** Gmail search syntax */
    query: string;
    /** 1-20, default 5 */
    limit?: number;
}
