// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {}
 */
export interface FindArtifactRequest {
    /** Exact vault id or name from list_vaults. Required whenever the key can reach more than one vault; never guess or use one client's vault for another. */
    vault?: string;
    /** Words from the title. Omit to list the most recent. */
    query?: string;
    /** Narrow to one kind of file */
    kind?: FindArtifactRequest.Kind;
    /** 1-25, default 10 */
    limit?: number;
}

export namespace FindArtifactRequest {
    /** Narrow to one kind of file */
    export const Kind = {
        Workbook: "workbook",
        Csv: "csv",
        Chart: "chart",
        Report: "report",
    } as const;
    export type Kind = (typeof Kind)[keyof typeof Kind];
}
