// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {}
 */
export interface GetBriefRequest {
    /** Exact vault id or name from list_vaults. Required whenever the key can reach more than one vault; never guess or use one client's vault for another. */
    vault?: string;
    /** Which brief (default daily) */
    kind?: GetBriefRequest.Kind;
}

export namespace GetBriefRequest {
    /** Which brief (default daily) */
    export const Kind = {
        Daily: "daily",
        WeeklyPlan: "weekly-plan",
        WeeklyDigest: "weekly-digest",
    } as const;
    export type Kind = (typeof Kind)[keyof typeof Kind];
}
