// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         entityId: "entityId"
 *     }
 */
export interface GetEntityRequest {
    /** Exact vault id or name from list_vaults. Required whenever the key can reach more than one vault; never guess or use one client's vault for another. */
    vault?: string;
    /** Entity id from a previous call */
    entityId: string;
    /** Include verbatim evidence quotes (default false) */
    includeEvidence?: boolean;
}
