// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         fileId: "fileId"
 *     }
 */
export interface GetFileRequest {
    /** Exact vault id or name from list_vaults. Required whenever the key can reach more than one vault; never guess or use one client's vault for another. */
    vault?: string;
    /** File id from list_files */
    fileId: string;
}
