// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         meetingId: "meetingId"
 *     }
 */
export interface GetTranscriptRequest {
    /** Exact vault id or name from list_vaults. Required whenever the key can reach more than one vault; never guess or use one client's vault for another. */
    vault?: string;
    /** Meeting id from list_meetings */
    meetingId: string;
    /** Chunk offset (default 0) */
    offset?: number;
    /** Chunks per page (default 20, max 50) */
    limit?: number;
}
