// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {}
 */
export interface ListSentEmailsRequest {
    /** Exact vault id or name from list_vaults. Required whenever the key can reach more than one vault; never guess or use one client's vault for another. */
    vault?: string;
    /** Narrow to one recipient */
    to?: string;
    /** 1-25, default 10 */
    limit?: number;
}
