// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {}
 */
export interface ListConflictsRequest {
    /** Exact vault id or name from list_vaults. Required whenever the key can reach more than one vault; never guess or use one client's vault for another. */
    vault?: string;
    /** Which conflicts (default open) */
    status?: ListConflictsRequest.Status;
}

export namespace ListConflictsRequest {
    /** Which conflicts (default open) */
    export const Status = {
        Open: "open",
        Resolved: "resolved",
        Dismissed: "dismissed",
        All: "all",
    } as const;
    export type Status = (typeof Status)[keyof typeof Status];
}
