// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {}
 */
export interface ListTasksRequest {
    /** Exact vault id or name from list_vaults. Required whenever the key can reach more than one vault; never guess or use one client's vault for another. */
    vault?: string;
    status?: ListTasksRequest.Status;
    /** Only tasks in this milestone (id from list_milestones) */
    milestoneId?: string;
}

export namespace ListTasksRequest {
    export const Status = {
        Todo: "todo",
        Doing: "doing",
        Done: "done",
        Blocked: "blocked",
        Open: "open",
    } as const;
    export type Status = (typeof Status)[keyof typeof Status];
}
