// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {}
 */
export interface ListPlanStepsRequest {
    /** Exact vault id or name from list_vaults. Required whenever the key can reach more than one vault; never guess or use one client's vault for another. */
    vault?: string;
}
