// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {}
 */
export interface ListFindingsRequest {
    /** Exact vault id or name from list_vaults. Required whenever the key can reach more than one vault; never guess or use one client's vault for another. */
    vault?: string;
    type?: ListFindingsRequest.Type;
    source?: ListFindingsRequest.Source;
    /** Only entities with evidence from this meeting */
    meetingId?: string;
    sort?: ListFindingsRequest.Sort;
    /** Page size (default 50, max 200) */
    limit?: number;
    /** nextCursor from the previous page */
    cursor?: string;
    /** Slim payload (default false) */
    compact?: boolean;
}

export namespace ListFindingsRequest {
    export const Type = {
        Department: "department",
        Person: "person",
        Process: "process",
        System: "system",
        Problem: "problem",
        Opportunity: "opportunity",
        Kpi: "kpi",
    } as const;
    export type Type = (typeof Type)[keyof typeof Type];
    export const Source = {
        Meeting: "meeting",
        File: "file",
        AgentAssumption: "agent-assumption",
        Unclear: "unclear",
    } as const;
    export type Source = (typeof Source)[keyof typeof Source];
    export const Sort = {
        Mentions: "mentions",
        Recent: "recent",
    } as const;
    export type Sort = (typeof Sort)[keyof typeof Sort];
}
