// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         query: "query"
 *     }
 */
export interface SearchAgentMemoryRequest {
    /** Exact vault id or name from list_vaults. Required whenever the key can reach more than one vault; never guess or use one client's vault for another. */
    vault?: string;
    /** What was talked about */
    query: string;
    /** Narrow to exchanges with one person */
    person_email?: string;
    /** 1-25, default 12 */
    limit?: number;
}
