// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         query: "query"
 *     }
 */
export interface SearchKnowledgeRequest {
    /** Exact vault id or name from list_vaults. Required whenever the key can reach more than one vault; never guess or use one client's vault for another. */
    vault?: string;
    /** Name or alias to search for */
    query: string;
    /** Optional entity type filter */
    type?: SearchKnowledgeRequest.Type;
}

export namespace SearchKnowledgeRequest {
    /** Optional entity type filter */
    export const Type = {
        Department: "department",
        Person: "person",
        Process: "process",
        System: "system",
        Problem: "problem",
        Opportunity: "opportunity",
        Kpi: "kpi",
    } as const;
    export type Type = (typeof Type)[keyof typeof Type];
}
