// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         conversation: "conversation"
 *     }
 */
export interface SuggestVaultScopeRequest {
    /** The recent user conversation that identifies a client, project, person or topic (maximum 12,000 trailing characters used). */
    conversation: string;
}
