// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         title: "title"
 *     }
 */
export interface AddTaskRequest {
    /** Exact vault id or name from list_vaults. Required whenever the key can reach more than one vault; never guess or use one client's vault for another. */
    vault?: string;
    /** Short actionable title (short and actionable) */
    title: string;
    /** Optional detail */
    description?: string;
    /** Responsible person or company */
    assigneeName?: string;
    /** T-shirt effort size */
    estimate?: AddTaskRequest.Estimate;
    priority?: AddTaskRequest.Priority;
    labels?: string[];
    checklist?: AddTaskRequest.Checklist.Item[];
    /** ISO date, e.g. 2026-08-15 */
    dueDate?: string;
    /** Milestone id from list_milestones */
    milestoneId?: string;
}

export namespace AddTaskRequest {
    /** T-shirt effort size */
    export const Estimate = {
        Xs: "xs",
        S: "s",
        M: "m",
        L: "l",
        Xl: "xl",
    } as const;
    export type Estimate = (typeof Estimate)[keyof typeof Estimate];
    export const Priority = {
        None: "none",
        Low: "low",
        Medium: "medium",
        High: "high",
        Urgent: "urgent",
    } as const;
    export type Priority = (typeof Priority)[keyof typeof Priority];
    export type Checklist = Checklist.Item[];

    export namespace Checklist {
        export interface Item {
            text: string;
            /** Default false */
            done?: boolean | undefined;
        }
    }
}
