// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {}
 */
export interface ExportReportRequest {
    /** Exact vault id or name from list_vaults. Required whenever the key can reach more than one vault; never guess or use one client's vault for another. */
    vault?: string;
    /** Default findings */
    dataset?: ExportReportRequest.Dataset;
    /** Default xlsx */
    format?: ExportReportRequest.Format;
}

export namespace ExportReportRequest {
    /** Default findings */
    export const Dataset = {
        Findings: "findings",
        Conflicts: "conflicts",
    } as const;
    export type Dataset = (typeof Dataset)[keyof typeof Dataset];
    /** Default xlsx */
    export const Format = {
        Xlsx: "xlsx",
        Csv: "csv",
        Pdf: "pdf",
    } as const;
    export type Format = (typeof Format)[keyof typeof Format];
}
