// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         title: "title",
 *         sheets: [{
 *                 "key": "value"
 *             }]
 *     }
 */
export interface ExportWorkbookRequest {
    /** Exact vault id or name from list_vaults. Required whenever the key can reach more than one vault; never guess or use one client's vault for another. */
    vault?: string;
    /** What the workbook is about */
    title: string;
    /** One entry per tab: {name, columns:[{header,key,numFmt?}], rows:[{<key>: value}]} */
    sheets: Record<string, unknown>[];
    /** Where the numbers came from; goes on the provenance sheet */
    sources?: string;
}
