// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         title: "title",
 *         vega_lite_spec: {
 *             "key": "value"
 *         }
 *     }
 */
export interface RenderChartRequest {
    /** Exact vault id or name from list_vaults. Required whenever the key can reach more than one vault; never guess or use one client's vault for another. */
    vault?: string;
    /** Chart title, shown on the image */
    title: string;
    /** Complete Vega-Lite v5 spec with inline data, e.g. {"data":{"values":[{"month":"2026-05","team":"Logistics","mentions":11}]},"mark":"line","encoding":{...}}. For month buckets set "timeUnit":"yearmonth" or the axis is labelled by day. */
    vega_lite_spec: Record<string, unknown>;
}
