// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         conflictId: "conflictId",
 *         status: "resolved"
 *     }
 */
export interface ResolveConflictRequest {
    /** Exact vault id or name from list_vaults. Required whenever the key can reach more than one vault; never guess or use one client's vault for another. */
    vault?: string;
    /** Conflict id from list_conflicts */
    conflictId: string;
    status: ResolveConflictRequest.Status;
    /** Resolution note: the validated answer, or why it was dismissed */
    note?: string;
}

export namespace ResolveConflictRequest {
    export const Status = {
        Resolved: "resolved",
        Dismissed: "dismissed",
        Open: "open",
    } as const;
    export type Status = (typeof Status)[keyof typeof Status];
}
