// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         title: "title",
 *         startIso: "startIso",
 *         attendees: ["attendees"]
 *     }
 */
export interface ScheduleMeetingRequest {
    /** Exact vault id or name from list_vaults. Required whenever the key can reach more than one vault; never guess or use one client's vault for another. */
    vault?: string;
    title: string;
    description?: string;
    /** ISO 8601 with offset, e.g. 2026-07-22T14:00:00-03:00 */
    startIso: string;
    /** 15 to 120 (default 30) */
    durationMinutes?: number;
    /** Attendee e-mails */
    attendees: string[];
}
