// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         to: "to",
 *         subject: "subject",
 *         body: "body"
 *     }
 */
export interface SendEmailRequest {
    /** Exact vault id or name from list_vaults. Required whenever the key can reach more than one vault; never guess or use one client's vault for another. */
    vault?: string;
    /** Recipient (must belong to this vault) */
    to: string;
    subject: string;
    /** Plain-text body */
    body: string;
    /** Copied recipients, subject to the same vault check as `to` */
    cc?: string[];
    /** artifactId values from find_artifact. Files only, never URLs. */
    attachmentIds?: string[];
    /** 'agent' (default) sends from the vault agent's address and takes several attachments; 'me' sends from the vault's connected Gmail and takes one. */
    sendAs?: SendEmailRequest.SendAs;
    /** Gmail thread id, to reply inside an existing conversation */
    replyToThreadId?: string;
    /** Message-ID of an earlier agent e-mail, to thread the reply */
    inReplyToMessageId?: string;
    /** Leave it in the connected Gmail's Drafts instead of sending. Nothing goes out. */
    asDraft?: boolean;
}

export namespace SendEmailRequest {
    /** 'agent' (default) sends from the vault agent's address and takes several attachments; 'me' sends from the vault's connected Gmail and takes one. */
    export const SendAs = {
        Agent: "agent",
        Me: "me",
    } as const;
    export type SendAs = (typeof SendAs)[keyof typeof SendAs];
}
