// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {}
 */
export interface UpdateTaskRequest {
    /** Exact vault id or name from list_vaults. Required whenever the key can reach more than one vault; never guess or use one client's vault for another. */
    vault?: string;
    /** Board reference: e.g. 'ACME-5', or just 5 */
    identifier?: UpdateTaskRequest.Identifier;
    /** Task id from list_tasks (alternative to identifier) */
    taskId?: string;
    title?: string;
    description?: string | null;
    status?: UpdateTaskRequest.Status;
    owner?: UpdateTaskRequest.Owner;
    assigneeName?: string | null;
    /** T-shirt effort size; null clears it */
    estimate?: UpdateTaskRequest.Estimate | null;
    priority?: UpdateTaskRequest.Priority;
    /** Replaces the label list ([] clears) */
    labels?: string[];
    /** Replaces the checklist ([] clears) */
    checklist?: UpdateTaskRequest.Checklist.Item[];
    /** ISO date; null clears */
    dueDate?: string | null;
    /** Milestone id from list_milestones; null clears */
    milestoneId?: string | null;
}

export namespace UpdateTaskRequest {
    /**
     * Board reference: e.g. 'ACME-5', or just 5
     */
    export type Identifier = string | number;
    export const Status = {
        Todo: "todo",
        Doing: "doing",
        Done: "done",
        Blocked: "blocked",
    } as const;
    export type Status = (typeof Status)[keyof typeof Status];
    export const Owner = {
        Client: "client",
        Us: "us",
    } as const;
    export type Owner = (typeof Owner)[keyof typeof Owner];
    /** T-shirt effort size; null clears it */
    export const Estimate = {
        Xs: "xs",
        S: "s",
        M: "m",
        L: "l",
        Xl: "xl",
    } as const;
    export type Estimate = (typeof Estimate)[keyof typeof Estimate];
    export const Priority = {
        None: "none",
        Low: "low",
        Medium: "medium",
        High: "high",
        Urgent: "urgent",
    } as const;
    export type Priority = (typeof Priority)[keyof typeof Priority];
    export type Checklist = Checklist.Item[];

    export namespace Checklist {
        export interface Item {
            text: string;
            done?: boolean | undefined;
        }
    }
}
