// This file was auto-generated by Fern from our API Definition.

import type { BaseClientOptions, BaseRequestOptions } from "../../../../BaseClient.js";
import { type NormalizedClientOptionsWithAuth, normalizeClientOptionsWithAuth } from "../../../../BaseClient.js";
import { mergeHeaders } from "../../../../core/headers.js";
import * as core from "../../../../core/index.js";
import { mergeAdditionalBodyParameters } from "../../../../core/requestBody.js";
import * as environments from "../../../../environments.js";
import { handleNonStatusCodeError } from "../../../../errors/handleNonStatusCodeError.js";
import * as errors from "../../../../errors/index.js";
import * as Alpha from "../../../index.js";

export declare namespace ActionsClient {
    export type Options = BaseClientOptions;

    export interface RequestOptions extends BaseRequestOptions {}
}

/**
 * Create approved tasks, artifacts, email, and calendar actions.
 */
export class ActionsClient {
    protected readonly _options: NormalizedClientOptionsWithAuth<ActionsClient.Options>;

    constructor(options: ActionsClient.Options = {}) {
        this._options = normalizeClientOptionsWithAuth(options);
    }

    /**
     * Close out a contradiction by id (from list_conflicts): status 'resolved' (validated with the client. say what the truth turned out to be in the note) or 'dismissed' (duplicate, transcription noise, not a real conflict. note why). Passing 'open' reopens one. Requires a manager API key.
     *
     * @param {Alpha.ResolveConflictRequest} request
     * @param {ActionsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Alpha.BadRequestError}
     * @throws {@link Alpha.UnauthorizedError}
     * @throws {@link Alpha.ForbiddenError}
     * @throws {@link Alpha.NotFoundError}
     * @throws {@link Alpha.TooManyRequestsError}
     * @throws {@link errors.AlphaError}
     * @throws {@link errors.AlphaTimeoutError}
     *
     * @example
     *     await client.actions.resolveConflict({
     *         conflictId: "conflictId",
     *         status: "resolved"
     *     })
     */
    public resolveConflict(
        request: Alpha.ResolveConflictRequest,
        requestOptions?: ActionsClient.RequestOptions,
    ): core.HttpResponsePromise<Alpha.DataResponse> {
        return core.HttpResponsePromise.fromPromise(this.__resolveConflict(request, requestOptions));
    }

    private async __resolveConflict(
        request: Alpha.ResolveConflictRequest,
        requestOptions?: ActionsClient.RequestOptions,
    ): Promise<core.WithRawResponse<Alpha.DataResponse>> {
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.AlphaEnvironment.Production,
                "v1/tools/resolve_conflict",
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            requestType: "json",
            body: mergeAdditionalBodyParameters(request, requestOptions?.additionalBodyParameters),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Alpha.DataResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new Alpha.BadRequestError(_response.error.body as Alpha.ErrorResponse, _response.rawResponse);
                case 401:
                    throw new Alpha.UnauthorizedError(
                        _response.error.body as Alpha.ErrorResponse,
                        _response.rawResponse,
                    );
                case 403:
                    throw new Alpha.ForbiddenError(_response.error.body as Alpha.ErrorResponse, _response.rawResponse);
                case 404:
                    throw new Alpha.NotFoundError(_response.error.body as Alpha.ErrorResponse, _response.rawResponse);
                case 429:
                    throw new Alpha.TooManyRequestsError(
                        _response.error.body as Alpha.ErrorResponse,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.AlphaError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "POST", "/v1/tools/resolve_conflict");
    }

    /**
     * Create a task on the vault's board. The owner may be a person's name or a company placeholder. Supports the full kanban surface: t-shirt estimate, priority, labels, checklist, due date and milestone (resolve ids with list_milestones). Requires a manager API key.
     *
     * @param {Alpha.AddTaskRequest} request
     * @param {ActionsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Alpha.BadRequestError}
     * @throws {@link Alpha.UnauthorizedError}
     * @throws {@link Alpha.ForbiddenError}
     * @throws {@link Alpha.NotFoundError}
     * @throws {@link Alpha.TooManyRequestsError}
     * @throws {@link errors.AlphaError}
     * @throws {@link errors.AlphaTimeoutError}
     *
     * @example
     *     await client.actions.addTask({
     *         title: "title"
     *     })
     */
    public addTask(
        request: Alpha.AddTaskRequest,
        requestOptions?: ActionsClient.RequestOptions,
    ): core.HttpResponsePromise<Alpha.DataResponse> {
        return core.HttpResponsePromise.fromPromise(this.__addTask(request, requestOptions));
    }

    private async __addTask(
        request: Alpha.AddTaskRequest,
        requestOptions?: ActionsClient.RequestOptions,
    ): Promise<core.WithRawResponse<Alpha.DataResponse>> {
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.AlphaEnvironment.Production,
                "v1/tools/add_task",
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            requestType: "json",
            body: mergeAdditionalBodyParameters(request, requestOptions?.additionalBodyParameters),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Alpha.DataResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new Alpha.BadRequestError(_response.error.body as Alpha.ErrorResponse, _response.rawResponse);
                case 401:
                    throw new Alpha.UnauthorizedError(
                        _response.error.body as Alpha.ErrorResponse,
                        _response.rawResponse,
                    );
                case 403:
                    throw new Alpha.ForbiddenError(_response.error.body as Alpha.ErrorResponse, _response.rawResponse);
                case 404:
                    throw new Alpha.NotFoundError(_response.error.body as Alpha.ErrorResponse, _response.rawResponse);
                case 429:
                    throw new Alpha.TooManyRequestsError(
                        _response.error.body as Alpha.ErrorResponse,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.AlphaError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "POST", "/v1/tools/add_task");
    }

    /**
     * Edit an existing task by its board identifier (for example 'ACME-5', or just 5; the prefix is whatever this vault uses) or by taskId from list_tasks. Fields: status, named owner, t-shirt estimate, priority, labels, checklist, due date, milestone, title and description. Pass null to clear a clearable field (estimate, dueDate, milestoneId, assigneeName, description). Requires a manager API key.
     *
     * @param {Alpha.UpdateTaskRequest} request
     * @param {ActionsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Alpha.BadRequestError}
     * @throws {@link Alpha.UnauthorizedError}
     * @throws {@link Alpha.ForbiddenError}
     * @throws {@link Alpha.NotFoundError}
     * @throws {@link Alpha.TooManyRequestsError}
     * @throws {@link errors.AlphaError}
     * @throws {@link errors.AlphaTimeoutError}
     *
     * @example
     *     await client.actions.updateTask()
     */
    public updateTask(
        request: Alpha.UpdateTaskRequest = {},
        requestOptions?: ActionsClient.RequestOptions,
    ): core.HttpResponsePromise<Alpha.DataResponse> {
        return core.HttpResponsePromise.fromPromise(this.__updateTask(request, requestOptions));
    }

    private async __updateTask(
        request: Alpha.UpdateTaskRequest = {},
        requestOptions?: ActionsClient.RequestOptions,
    ): Promise<core.WithRawResponse<Alpha.DataResponse>> {
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.AlphaEnvironment.Production,
                "v1/tools/update_task",
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            requestType: "json",
            body: mergeAdditionalBodyParameters(request, requestOptions?.additionalBodyParameters),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Alpha.DataResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new Alpha.BadRequestError(_response.error.body as Alpha.ErrorResponse, _response.rawResponse);
                case 401:
                    throw new Alpha.UnauthorizedError(
                        _response.error.body as Alpha.ErrorResponse,
                        _response.rawResponse,
                    );
                case 403:
                    throw new Alpha.ForbiddenError(_response.error.body as Alpha.ErrorResponse, _response.rawResponse);
                case 404:
                    throw new Alpha.NotFoundError(_response.error.body as Alpha.ErrorResponse, _response.rawResponse);
                case 429:
                    throw new Alpha.TooManyRequestsError(
                        _response.error.body as Alpha.ErrorResponse,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.AlphaError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "POST", "/v1/tools/update_task");
    }

    /**
     * Send an e-mail from the vault agent's mailbox to a VAULT MEMBER or registered stakeholder. Can carry files: pass artifact ids from find_artifact. Can also reply INSIDE an existing thread, or be left as a draft in the connected Gmail account for a person to review and send. Requires a manager API key.
     *
     * @param {Alpha.SendEmailRequest} request
     * @param {ActionsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Alpha.BadRequestError}
     * @throws {@link Alpha.UnauthorizedError}
     * @throws {@link Alpha.ForbiddenError}
     * @throws {@link Alpha.NotFoundError}
     * @throws {@link Alpha.TooManyRequestsError}
     * @throws {@link errors.AlphaError}
     * @throws {@link errors.AlphaTimeoutError}
     *
     * @example
     *     await client.actions.sendEmail({
     *         to: "to",
     *         subject: "subject",
     *         body: "body"
     *     })
     */
    public sendEmail(
        request: Alpha.SendEmailRequest,
        requestOptions?: ActionsClient.RequestOptions,
    ): core.HttpResponsePromise<Alpha.DataResponse> {
        return core.HttpResponsePromise.fromPromise(this.__sendEmail(request, requestOptions));
    }

    private async __sendEmail(
        request: Alpha.SendEmailRequest,
        requestOptions?: ActionsClient.RequestOptions,
    ): Promise<core.WithRawResponse<Alpha.DataResponse>> {
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.AlphaEnvironment.Production,
                "v1/tools/send_email",
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            requestType: "json",
            body: mergeAdditionalBodyParameters(request, requestOptions?.additionalBodyParameters),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Alpha.DataResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new Alpha.BadRequestError(_response.error.body as Alpha.ErrorResponse, _response.rawResponse);
                case 401:
                    throw new Alpha.UnauthorizedError(
                        _response.error.body as Alpha.ErrorResponse,
                        _response.rawResponse,
                    );
                case 403:
                    throw new Alpha.ForbiddenError(_response.error.body as Alpha.ErrorResponse, _response.rawResponse);
                case 404:
                    throw new Alpha.NotFoundError(_response.error.body as Alpha.ErrorResponse, _response.rawResponse);
                case 429:
                    throw new Alpha.TooManyRequestsError(
                        _response.error.body as Alpha.ErrorResponse,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.AlphaError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "POST", "/v1/tools/send_email");
    }

    /**
     * Build a styled multi-sheet Excel workbook (.xlsx) from rows you provide, store it in this vault, and return a url plus an artifactId that send_email can attach. Use it when the answer is a table someone will sort, filter or forward. Formatting, freezing and the provenance sheet are automatic. Requires a manager API key, since it stores a file.
     *
     * @param {Alpha.ExportWorkbookRequest} request
     * @param {ActionsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Alpha.BadRequestError}
     * @throws {@link Alpha.UnauthorizedError}
     * @throws {@link Alpha.ForbiddenError}
     * @throws {@link Alpha.NotFoundError}
     * @throws {@link Alpha.TooManyRequestsError}
     * @throws {@link errors.AlphaError}
     * @throws {@link errors.AlphaTimeoutError}
     *
     * @example
     *     await client.actions.exportWorkbook({
     *         title: "title",
     *         sheets: [{
     *                 "key": "value"
     *             }]
     *     })
     */
    public exportWorkbook(
        request: Alpha.ExportWorkbookRequest,
        requestOptions?: ActionsClient.RequestOptions,
    ): core.HttpResponsePromise<Alpha.DataResponse> {
        return core.HttpResponsePromise.fromPromise(this.__exportWorkbook(request, requestOptions));
    }

    private async __exportWorkbook(
        request: Alpha.ExportWorkbookRequest,
        requestOptions?: ActionsClient.RequestOptions,
    ): Promise<core.WithRawResponse<Alpha.DataResponse>> {
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.AlphaEnvironment.Production,
                "v1/tools/export_workbook",
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            requestType: "json",
            body: mergeAdditionalBodyParameters(request, requestOptions?.additionalBodyParameters),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Alpha.DataResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new Alpha.BadRequestError(_response.error.body as Alpha.ErrorResponse, _response.rawResponse);
                case 401:
                    throw new Alpha.UnauthorizedError(
                        _response.error.body as Alpha.ErrorResponse,
                        _response.rawResponse,
                    );
                case 403:
                    throw new Alpha.ForbiddenError(_response.error.body as Alpha.ErrorResponse, _response.rawResponse);
                case 404:
                    throw new Alpha.NotFoundError(_response.error.body as Alpha.ErrorResponse, _response.rawResponse);
                case 429:
                    throw new Alpha.TooManyRequestsError(
                        _response.error.body as Alpha.ErrorResponse,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.AlphaError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "POST", "/v1/tools/export_workbook");
    }

    /**
     * Export a whole dataset from this vault as a file: every finding, or every contradiction, as xlsx, csv or PDF. The only path that produces a PDF. For a table you assembled yourself, use export_workbook. Returns a url and an artifactId that send_email can attach. Requires a manager API key, since it stores a file.
     *
     * @param {Alpha.ExportReportRequest} request
     * @param {ActionsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Alpha.BadRequestError}
     * @throws {@link Alpha.UnauthorizedError}
     * @throws {@link Alpha.ForbiddenError}
     * @throws {@link Alpha.NotFoundError}
     * @throws {@link Alpha.TooManyRequestsError}
     * @throws {@link errors.AlphaError}
     * @throws {@link errors.AlphaTimeoutError}
     *
     * @example
     *     await client.actions.exportReport()
     */
    public exportReport(
        request: Alpha.ExportReportRequest = {},
        requestOptions?: ActionsClient.RequestOptions,
    ): core.HttpResponsePromise<Alpha.DataResponse> {
        return core.HttpResponsePromise.fromPromise(this.__exportReport(request, requestOptions));
    }

    private async __exportReport(
        request: Alpha.ExportReportRequest = {},
        requestOptions?: ActionsClient.RequestOptions,
    ): Promise<core.WithRawResponse<Alpha.DataResponse>> {
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.AlphaEnvironment.Production,
                "v1/tools/export_report",
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            requestType: "json",
            body: mergeAdditionalBodyParameters(request, requestOptions?.additionalBodyParameters),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Alpha.DataResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new Alpha.BadRequestError(_response.error.body as Alpha.ErrorResponse, _response.rawResponse);
                case 401:
                    throw new Alpha.UnauthorizedError(
                        _response.error.body as Alpha.ErrorResponse,
                        _response.rawResponse,
                    );
                case 403:
                    throw new Alpha.ForbiddenError(_response.error.body as Alpha.ErrorResponse, _response.rawResponse);
                case 404:
                    throw new Alpha.NotFoundError(_response.error.body as Alpha.ErrorResponse, _response.rawResponse);
                case 429:
                    throw new Alpha.TooManyRequestsError(
                        _response.error.body as Alpha.ErrorResponse,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.AlphaError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "POST", "/v1/tools/export_report");
    }

    /**
     * Render a chart PNG from a Vega-Lite v5 spec with the data inline, and store it as an artifact in this vault. Returns a url to embed and an artifactId that send_email can attach. Do not set colors: the vault's theme is applied automatically. Match the mark to the question. anything over time is a line, a ranking is a sorted horizontal bar, part-of-whole is an arc. Requires a manager API key, since it stores a file.
     *
     * @param {Alpha.RenderChartRequest} request
     * @param {ActionsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Alpha.BadRequestError}
     * @throws {@link Alpha.UnauthorizedError}
     * @throws {@link Alpha.ForbiddenError}
     * @throws {@link Alpha.NotFoundError}
     * @throws {@link Alpha.TooManyRequestsError}
     * @throws {@link errors.AlphaError}
     * @throws {@link errors.AlphaTimeoutError}
     *
     * @example
     *     await client.actions.renderChart({
     *         title: "title",
     *         vega_lite_spec: {
     *             "key": "value"
     *         }
     *     })
     */
    public renderChart(
        request: Alpha.RenderChartRequest,
        requestOptions?: ActionsClient.RequestOptions,
    ): core.HttpResponsePromise<Alpha.DataResponse> {
        return core.HttpResponsePromise.fromPromise(this.__renderChart(request, requestOptions));
    }

    private async __renderChart(
        request: Alpha.RenderChartRequest,
        requestOptions?: ActionsClient.RequestOptions,
    ): Promise<core.WithRawResponse<Alpha.DataResponse>> {
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.AlphaEnvironment.Production,
                "v1/tools/render_chart",
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            requestType: "json",
            body: mergeAdditionalBodyParameters(request, requestOptions?.additionalBodyParameters),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Alpha.DataResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new Alpha.BadRequestError(_response.error.body as Alpha.ErrorResponse, _response.rawResponse);
                case 401:
                    throw new Alpha.UnauthorizedError(
                        _response.error.body as Alpha.ErrorResponse,
                        _response.rawResponse,
                    );
                case 403:
                    throw new Alpha.ForbiddenError(_response.error.body as Alpha.ErrorResponse, _response.rawResponse);
                case 404:
                    throw new Alpha.NotFoundError(_response.error.body as Alpha.ErrorResponse, _response.rawResponse);
                case 429:
                    throw new Alpha.TooManyRequestsError(
                        _response.error.body as Alpha.ErrorResponse,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.AlphaError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "POST", "/v1/tools/render_chart");
    }

    /**
     * Create a Google Calendar event with a Meet link via the project's connected calendar. Requires a manager API key.
     *
     * @param {Alpha.ScheduleMeetingRequest} request
     * @param {ActionsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Alpha.BadRequestError}
     * @throws {@link Alpha.UnauthorizedError}
     * @throws {@link Alpha.ForbiddenError}
     * @throws {@link Alpha.NotFoundError}
     * @throws {@link Alpha.TooManyRequestsError}
     * @throws {@link errors.AlphaError}
     * @throws {@link errors.AlphaTimeoutError}
     *
     * @example
     *     await client.actions.scheduleMeeting({
     *         title: "title",
     *         startIso: "startIso",
     *         attendees: ["attendees"]
     *     })
     */
    public scheduleMeeting(
        request: Alpha.ScheduleMeetingRequest,
        requestOptions?: ActionsClient.RequestOptions,
    ): core.HttpResponsePromise<Alpha.DataResponse> {
        return core.HttpResponsePromise.fromPromise(this.__scheduleMeeting(request, requestOptions));
    }

    private async __scheduleMeeting(
        request: Alpha.ScheduleMeetingRequest,
        requestOptions?: ActionsClient.RequestOptions,
    ): Promise<core.WithRawResponse<Alpha.DataResponse>> {
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.AlphaEnvironment.Production,
                "v1/tools/schedule_meeting",
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            requestType: "json",
            body: mergeAdditionalBodyParameters(request, requestOptions?.additionalBodyParameters),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Alpha.DataResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new Alpha.BadRequestError(_response.error.body as Alpha.ErrorResponse, _response.rawResponse);
                case 401:
                    throw new Alpha.UnauthorizedError(
                        _response.error.body as Alpha.ErrorResponse,
                        _response.rawResponse,
                    );
                case 403:
                    throw new Alpha.ForbiddenError(_response.error.body as Alpha.ErrorResponse, _response.rawResponse);
                case 404:
                    throw new Alpha.NotFoundError(_response.error.body as Alpha.ErrorResponse, _response.rawResponse);
                case 429:
                    throw new Alpha.TooManyRequestsError(
                        _response.error.body as Alpha.ErrorResponse,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.AlphaError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "POST", "/v1/tools/schedule_meeting");
    }
}
