// This file was auto-generated by Fern from our API Definition.

export interface ApiIndexResponse {
    name: string;
    version: string;
    authentication: string;
    endpoints: ApiIndexResponse.Endpoints;
}

export namespace ApiIndexResponse {
    export interface Endpoints {
        vaults: string;
        tools: string;
        invokeTool: string;
        openapi: string;
        mcp: string;
    }
}
