// This file was auto-generated by Fern from our API Definition.

export interface DataResponse {
    /** The result returned by the selected Alpha tool. */
    data: DataResponse.Data;
}

export namespace DataResponse {
    /**
     * The result returned by the selected Alpha tool.
     */
    export type Data = Record<string, unknown> | Record<string, unknown>[];
}
