// This file was auto-generated by Fern from our API Definition.

import * as Alpha from "../../src/api/index";
import { AlphaClient } from "../../src/Client";
import { mockServerPool } from "../mock-server/MockServerPool";

describe("ActionsClient", () => {
    test("resolveConflict (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new AlphaClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { conflictId: "conflictId", status: "resolved" };
        const rawResponseBody = { data: { key: "value" } };

        server
            .mockEndpoint()
            .post("/v1/tools/resolve_conflict")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.actions.resolveConflict({
            conflictId: "conflictId",
            status: "resolved",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("resolveConflict (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new AlphaClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { conflictId: "conflictId", status: "resolved" };
        const rawResponseBody = { error: { code: "code", message: "message", requestId: "requestId" } };

        server
            .mockEndpoint()
            .post("/v1/tools/resolve_conflict")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.actions.resolveConflict({
                conflictId: "conflictId",
                status: "resolved",
            });
        }).rejects.toThrow(Alpha.BadRequestError);
    });

    test("resolveConflict (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new AlphaClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { conflictId: "conflictId", status: "resolved" };
        const rawResponseBody = { error: { code: "code", message: "message", requestId: "requestId" } };

        server
            .mockEndpoint()
            .post("/v1/tools/resolve_conflict")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.actions.resolveConflict({
                conflictId: "conflictId",
                status: "resolved",
            });
        }).rejects.toThrow(Alpha.UnauthorizedError);
    });

    test("resolveConflict (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new AlphaClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { conflictId: "conflictId", status: "resolved" };
        const rawResponseBody = { error: { code: "code", message: "message", requestId: "requestId" } };

        server
            .mockEndpoint()
            .post("/v1/tools/resolve_conflict")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.actions.resolveConflict({
                conflictId: "conflictId",
                status: "resolved",
            });
        }).rejects.toThrow(Alpha.ForbiddenError);
    });

    test("resolveConflict (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new AlphaClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { conflictId: "conflictId", status: "resolved" };
        const rawResponseBody = { error: { code: "code", message: "message", requestId: "requestId" } };

        server
            .mockEndpoint()
            .post("/v1/tools/resolve_conflict")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.actions.resolveConflict({
                conflictId: "conflictId",
                status: "resolved",
            });
        }).rejects.toThrow(Alpha.NotFoundError);
    });

    test("resolveConflict (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new AlphaClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { conflictId: "conflictId", status: "resolved" };
        const rawResponseBody = { error: { code: "code", message: "message", requestId: "requestId" } };

        server
            .mockEndpoint()
            .post("/v1/tools/resolve_conflict")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(429)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.actions.resolveConflict({
                conflictId: "conflictId",
                status: "resolved",
            });
        }).rejects.toThrow(Alpha.TooManyRequestsError);
    });

    test("addTask (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new AlphaClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { title: "title" };
        const rawResponseBody = { data: { key: "value" } };

        server
            .mockEndpoint()
            .post("/v1/tools/add_task")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.actions.addTask({
            title: "title",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("addTask (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new AlphaClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { title: "title" };
        const rawResponseBody = { error: { code: "code", message: "message", requestId: "requestId" } };

        server
            .mockEndpoint()
            .post("/v1/tools/add_task")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.actions.addTask({
                title: "title",
            });
        }).rejects.toThrow(Alpha.BadRequestError);
    });

    test("addTask (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new AlphaClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { title: "title" };
        const rawResponseBody = { error: { code: "code", message: "message", requestId: "requestId" } };

        server
            .mockEndpoint()
            .post("/v1/tools/add_task")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.actions.addTask({
                title: "title",
            });
        }).rejects.toThrow(Alpha.UnauthorizedError);
    });

    test("addTask (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new AlphaClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { title: "title" };
        const rawResponseBody = { error: { code: "code", message: "message", requestId: "requestId" } };

        server
            .mockEndpoint()
            .post("/v1/tools/add_task")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.actions.addTask({
                title: "title",
            });
        }).rejects.toThrow(Alpha.ForbiddenError);
    });

    test("addTask (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new AlphaClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { title: "title" };
        const rawResponseBody = { error: { code: "code", message: "message", requestId: "requestId" } };

        server
            .mockEndpoint()
            .post("/v1/tools/add_task")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.actions.addTask({
                title: "title",
            });
        }).rejects.toThrow(Alpha.NotFoundError);
    });

    test("addTask (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new AlphaClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { title: "title" };
        const rawResponseBody = { error: { code: "code", message: "message", requestId: "requestId" } };

        server
            .mockEndpoint()
            .post("/v1/tools/add_task")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(429)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.actions.addTask({
                title: "title",
            });
        }).rejects.toThrow(Alpha.TooManyRequestsError);
    });

    test("updateTask (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new AlphaClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = { data: { key: "value" } };

        server
            .mockEndpoint()
            .post("/v1/tools/update_task")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.actions.updateTask();
        expect(response).toEqual(rawResponseBody);
    });

    test("updateTask (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new AlphaClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = { error: { code: "code", message: "message", requestId: "requestId" } };

        server
            .mockEndpoint()
            .post("/v1/tools/update_task")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.actions.updateTask();
        }).rejects.toThrow(Alpha.BadRequestError);
    });

    test("updateTask (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new AlphaClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = { error: { code: "code", message: "message", requestId: "requestId" } };

        server
            .mockEndpoint()
            .post("/v1/tools/update_task")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.actions.updateTask();
        }).rejects.toThrow(Alpha.UnauthorizedError);
    });

    test("updateTask (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new AlphaClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = { error: { code: "code", message: "message", requestId: "requestId" } };

        server
            .mockEndpoint()
            .post("/v1/tools/update_task")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.actions.updateTask();
        }).rejects.toThrow(Alpha.ForbiddenError);
    });

    test("updateTask (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new AlphaClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = { error: { code: "code", message: "message", requestId: "requestId" } };

        server
            .mockEndpoint()
            .post("/v1/tools/update_task")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.actions.updateTask();
        }).rejects.toThrow(Alpha.NotFoundError);
    });

    test("updateTask (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new AlphaClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = { error: { code: "code", message: "message", requestId: "requestId" } };

        server
            .mockEndpoint()
            .post("/v1/tools/update_task")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(429)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.actions.updateTask();
        }).rejects.toThrow(Alpha.TooManyRequestsError);
    });

    test("sendEmail (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new AlphaClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { to: "to", subject: "subject", body: "body" };
        const rawResponseBody = { data: { key: "value" } };

        server
            .mockEndpoint()
            .post("/v1/tools/send_email")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.actions.sendEmail({
            to: "to",
            subject: "subject",
            body: "body",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("sendEmail (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new AlphaClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { to: "to", subject: "subject", body: "body" };
        const rawResponseBody = { error: { code: "code", message: "message", requestId: "requestId" } };

        server
            .mockEndpoint()
            .post("/v1/tools/send_email")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.actions.sendEmail({
                to: "to",
                subject: "subject",
                body: "body",
            });
        }).rejects.toThrow(Alpha.BadRequestError);
    });

    test("sendEmail (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new AlphaClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { to: "to", subject: "subject", body: "body" };
        const rawResponseBody = { error: { code: "code", message: "message", requestId: "requestId" } };

        server
            .mockEndpoint()
            .post("/v1/tools/send_email")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.actions.sendEmail({
                to: "to",
                subject: "subject",
                body: "body",
            });
        }).rejects.toThrow(Alpha.UnauthorizedError);
    });

    test("sendEmail (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new AlphaClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { to: "to", subject: "subject", body: "body" };
        const rawResponseBody = { error: { code: "code", message: "message", requestId: "requestId" } };

        server
            .mockEndpoint()
            .post("/v1/tools/send_email")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.actions.sendEmail({
                to: "to",
                subject: "subject",
                body: "body",
            });
        }).rejects.toThrow(Alpha.ForbiddenError);
    });

    test("sendEmail (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new AlphaClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { to: "to", subject: "subject", body: "body" };
        const rawResponseBody = { error: { code: "code", message: "message", requestId: "requestId" } };

        server
            .mockEndpoint()
            .post("/v1/tools/send_email")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.actions.sendEmail({
                to: "to",
                subject: "subject",
                body: "body",
            });
        }).rejects.toThrow(Alpha.NotFoundError);
    });

    test("sendEmail (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new AlphaClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { to: "to", subject: "subject", body: "body" };
        const rawResponseBody = { error: { code: "code", message: "message", requestId: "requestId" } };

        server
            .mockEndpoint()
            .post("/v1/tools/send_email")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(429)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.actions.sendEmail({
                to: "to",
                subject: "subject",
                body: "body",
            });
        }).rejects.toThrow(Alpha.TooManyRequestsError);
    });

    test("exportWorkbook (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new AlphaClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { title: "title", sheets: [{ key: "value" }] };
        const rawResponseBody = { data: { key: "value" } };

        server
            .mockEndpoint()
            .post("/v1/tools/export_workbook")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.actions.exportWorkbook({
            title: "title",
            sheets: [
                {
                    key: "value",
                },
            ],
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("exportWorkbook (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new AlphaClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { title: "title", sheets: [{ sheets: { key: "value" } }, { sheets: { key: "value" } }] };
        const rawResponseBody = { error: { code: "code", message: "message", requestId: "requestId" } };

        server
            .mockEndpoint()
            .post("/v1/tools/export_workbook")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.actions.exportWorkbook({
                title: "title",
                sheets: [
                    {
                        sheets: {
                            key: "value",
                        },
                    },
                    {
                        sheets: {
                            key: "value",
                        },
                    },
                ],
            });
        }).rejects.toThrow(Alpha.BadRequestError);
    });

    test("exportWorkbook (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new AlphaClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { title: "title", sheets: [{ sheets: { key: "value" } }, { sheets: { key: "value" } }] };
        const rawResponseBody = { error: { code: "code", message: "message", requestId: "requestId" } };

        server
            .mockEndpoint()
            .post("/v1/tools/export_workbook")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.actions.exportWorkbook({
                title: "title",
                sheets: [
                    {
                        sheets: {
                            key: "value",
                        },
                    },
                    {
                        sheets: {
                            key: "value",
                        },
                    },
                ],
            });
        }).rejects.toThrow(Alpha.UnauthorizedError);
    });

    test("exportWorkbook (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new AlphaClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { title: "title", sheets: [{ sheets: { key: "value" } }, { sheets: { key: "value" } }] };
        const rawResponseBody = { error: { code: "code", message: "message", requestId: "requestId" } };

        server
            .mockEndpoint()
            .post("/v1/tools/export_workbook")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.actions.exportWorkbook({
                title: "title",
                sheets: [
                    {
                        sheets: {
                            key: "value",
                        },
                    },
                    {
                        sheets: {
                            key: "value",
                        },
                    },
                ],
            });
        }).rejects.toThrow(Alpha.ForbiddenError);
    });

    test("exportWorkbook (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new AlphaClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { title: "title", sheets: [{ sheets: { key: "value" } }, { sheets: { key: "value" } }] };
        const rawResponseBody = { error: { code: "code", message: "message", requestId: "requestId" } };

        server
            .mockEndpoint()
            .post("/v1/tools/export_workbook")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.actions.exportWorkbook({
                title: "title",
                sheets: [
                    {
                        sheets: {
                            key: "value",
                        },
                    },
                    {
                        sheets: {
                            key: "value",
                        },
                    },
                ],
            });
        }).rejects.toThrow(Alpha.NotFoundError);
    });

    test("exportWorkbook (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new AlphaClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { title: "title", sheets: [{ sheets: { key: "value" } }, { sheets: { key: "value" } }] };
        const rawResponseBody = { error: { code: "code", message: "message", requestId: "requestId" } };

        server
            .mockEndpoint()
            .post("/v1/tools/export_workbook")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(429)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.actions.exportWorkbook({
                title: "title",
                sheets: [
                    {
                        sheets: {
                            key: "value",
                        },
                    },
                    {
                        sheets: {
                            key: "value",
                        },
                    },
                ],
            });
        }).rejects.toThrow(Alpha.TooManyRequestsError);
    });

    test("exportReport (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new AlphaClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = { data: { key: "value" } };

        server
            .mockEndpoint()
            .post("/v1/tools/export_report")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.actions.exportReport();
        expect(response).toEqual(rawResponseBody);
    });

    test("exportReport (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new AlphaClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = { error: { code: "code", message: "message", requestId: "requestId" } };

        server
            .mockEndpoint()
            .post("/v1/tools/export_report")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.actions.exportReport();
        }).rejects.toThrow(Alpha.BadRequestError);
    });

    test("exportReport (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new AlphaClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = { error: { code: "code", message: "message", requestId: "requestId" } };

        server
            .mockEndpoint()
            .post("/v1/tools/export_report")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.actions.exportReport();
        }).rejects.toThrow(Alpha.UnauthorizedError);
    });

    test("exportReport (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new AlphaClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = { error: { code: "code", message: "message", requestId: "requestId" } };

        server
            .mockEndpoint()
            .post("/v1/tools/export_report")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.actions.exportReport();
        }).rejects.toThrow(Alpha.ForbiddenError);
    });

    test("exportReport (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new AlphaClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = { error: { code: "code", message: "message", requestId: "requestId" } };

        server
            .mockEndpoint()
            .post("/v1/tools/export_report")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.actions.exportReport();
        }).rejects.toThrow(Alpha.NotFoundError);
    });

    test("exportReport (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new AlphaClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = { error: { code: "code", message: "message", requestId: "requestId" } };

        server
            .mockEndpoint()
            .post("/v1/tools/export_report")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(429)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.actions.exportReport();
        }).rejects.toThrow(Alpha.TooManyRequestsError);
    });

    test("renderChart (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new AlphaClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { title: "title", vega_lite_spec: { key: "value" } };
        const rawResponseBody = { data: { key: "value" } };

        server
            .mockEndpoint()
            .post("/v1/tools/render_chart")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.actions.renderChart({
            title: "title",
            vega_lite_spec: {
                key: "value",
            },
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("renderChart (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new AlphaClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { title: "title", vega_lite_spec: { vega_lite_spec: { key: "value" } } };
        const rawResponseBody = { error: { code: "code", message: "message", requestId: "requestId" } };

        server
            .mockEndpoint()
            .post("/v1/tools/render_chart")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.actions.renderChart({
                title: "title",
                vega_lite_spec: {
                    vega_lite_spec: {
                        key: "value",
                    },
                },
            });
        }).rejects.toThrow(Alpha.BadRequestError);
    });

    test("renderChart (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new AlphaClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { title: "title", vega_lite_spec: { vega_lite_spec: { key: "value" } } };
        const rawResponseBody = { error: { code: "code", message: "message", requestId: "requestId" } };

        server
            .mockEndpoint()
            .post("/v1/tools/render_chart")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.actions.renderChart({
                title: "title",
                vega_lite_spec: {
                    vega_lite_spec: {
                        key: "value",
                    },
                },
            });
        }).rejects.toThrow(Alpha.UnauthorizedError);
    });

    test("renderChart (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new AlphaClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { title: "title", vega_lite_spec: { vega_lite_spec: { key: "value" } } };
        const rawResponseBody = { error: { code: "code", message: "message", requestId: "requestId" } };

        server
            .mockEndpoint()
            .post("/v1/tools/render_chart")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.actions.renderChart({
                title: "title",
                vega_lite_spec: {
                    vega_lite_spec: {
                        key: "value",
                    },
                },
            });
        }).rejects.toThrow(Alpha.ForbiddenError);
    });

    test("renderChart (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new AlphaClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { title: "title", vega_lite_spec: { vega_lite_spec: { key: "value" } } };
        const rawResponseBody = { error: { code: "code", message: "message", requestId: "requestId" } };

        server
            .mockEndpoint()
            .post("/v1/tools/render_chart")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.actions.renderChart({
                title: "title",
                vega_lite_spec: {
                    vega_lite_spec: {
                        key: "value",
                    },
                },
            });
        }).rejects.toThrow(Alpha.NotFoundError);
    });

    test("renderChart (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new AlphaClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { title: "title", vega_lite_spec: { vega_lite_spec: { key: "value" } } };
        const rawResponseBody = { error: { code: "code", message: "message", requestId: "requestId" } };

        server
            .mockEndpoint()
            .post("/v1/tools/render_chart")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(429)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.actions.renderChart({
                title: "title",
                vega_lite_spec: {
                    vega_lite_spec: {
                        key: "value",
                    },
                },
            });
        }).rejects.toThrow(Alpha.TooManyRequestsError);
    });

    test("scheduleMeeting (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new AlphaClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { title: "title", startIso: "startIso", attendees: ["attendees"] };
        const rawResponseBody = { data: { key: "value" } };

        server
            .mockEndpoint()
            .post("/v1/tools/schedule_meeting")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.actions.scheduleMeeting({
            title: "title",
            startIso: "startIso",
            attendees: ["attendees"],
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("scheduleMeeting (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new AlphaClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { title: "title", startIso: "startIso", attendees: ["attendees", "attendees"] };
        const rawResponseBody = { error: { code: "code", message: "message", requestId: "requestId" } };

        server
            .mockEndpoint()
            .post("/v1/tools/schedule_meeting")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.actions.scheduleMeeting({
                title: "title",
                startIso: "startIso",
                attendees: ["attendees", "attendees"],
            });
        }).rejects.toThrow(Alpha.BadRequestError);
    });

    test("scheduleMeeting (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new AlphaClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { title: "title", startIso: "startIso", attendees: ["attendees", "attendees"] };
        const rawResponseBody = { error: { code: "code", message: "message", requestId: "requestId" } };

        server
            .mockEndpoint()
            .post("/v1/tools/schedule_meeting")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.actions.scheduleMeeting({
                title: "title",
                startIso: "startIso",
                attendees: ["attendees", "attendees"],
            });
        }).rejects.toThrow(Alpha.UnauthorizedError);
    });

    test("scheduleMeeting (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new AlphaClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { title: "title", startIso: "startIso", attendees: ["attendees", "attendees"] };
        const rawResponseBody = { error: { code: "code", message: "message", requestId: "requestId" } };

        server
            .mockEndpoint()
            .post("/v1/tools/schedule_meeting")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.actions.scheduleMeeting({
                title: "title",
                startIso: "startIso",
                attendees: ["attendees", "attendees"],
            });
        }).rejects.toThrow(Alpha.ForbiddenError);
    });

    test("scheduleMeeting (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new AlphaClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { title: "title", startIso: "startIso", attendees: ["attendees", "attendees"] };
        const rawResponseBody = { error: { code: "code", message: "message", requestId: "requestId" } };

        server
            .mockEndpoint()
            .post("/v1/tools/schedule_meeting")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.actions.scheduleMeeting({
                title: "title",
                startIso: "startIso",
                attendees: ["attendees", "attendees"],
            });
        }).rejects.toThrow(Alpha.NotFoundError);
    });

    test("scheduleMeeting (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new AlphaClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { title: "title", startIso: "startIso", attendees: ["attendees", "attendees"] };
        const rawResponseBody = { error: { code: "code", message: "message", requestId: "requestId" } };

        server
            .mockEndpoint()
            .post("/v1/tools/schedule_meeting")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(429)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.actions.scheduleMeeting({
                title: "title",
                startIso: "startIso",
                attendees: ["attendees", "attendees"],
            });
        }).rejects.toThrow(Alpha.TooManyRequestsError);
    });
});
