// This file was auto-generated by Fern from our API Definition.

import * as Alpha from "../../src/api/index";
import { AlphaClient } from "../../src/Client";
import { mockServerPool } from "../mock-server/MockServerPool";

describe("MetadataClient", () => {
    test("getApiIndex", async () => {
        const server = mockServerPool.createServer();
        const client = new AlphaClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            name: "Alpha API",
            version: "2026-09-02",
            authentication: "Bearer token",
            endpoints: { vaults: "vaults", tools: "tools", invokeTool: "invokeTool", openapi: "openapi", mcp: "mcp" },
        };

        server.mockEndpoint().get("/v1").respondWith().statusCode(200).jsonBody(rawResponseBody).build();

        const response = await client.metadata.getApiIndex();
        expect(response).toEqual(rawResponseBody);
    });

    test("listTools (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new AlphaClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { data: { key: "value" } };

        server.mockEndpoint().get("/v1/tools").respondWith().statusCode(200).jsonBody(rawResponseBody).build();

        const response = await client.metadata.listTools();
        expect(response).toEqual(rawResponseBody);
    });

    test("listTools (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new AlphaClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "code", message: "message", requestId: "requestId" } };

        server.mockEndpoint().get("/v1/tools").respondWith().statusCode(400).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.metadata.listTools();
        }).rejects.toThrow(Alpha.BadRequestError);
    });

    test("listTools (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new AlphaClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "code", message: "message", requestId: "requestId" } };

        server.mockEndpoint().get("/v1/tools").respondWith().statusCode(401).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.metadata.listTools();
        }).rejects.toThrow(Alpha.UnauthorizedError);
    });

    test("listTools (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new AlphaClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "code", message: "message", requestId: "requestId" } };

        server.mockEndpoint().get("/v1/tools").respondWith().statusCode(403).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.metadata.listTools();
        }).rejects.toThrow(Alpha.ForbiddenError);
    });

    test("listTools (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new AlphaClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "code", message: "message", requestId: "requestId" } };

        server.mockEndpoint().get("/v1/tools").respondWith().statusCode(404).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.metadata.listTools();
        }).rejects.toThrow(Alpha.NotFoundError);
    });

    test("listTools (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new AlphaClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "code", message: "message", requestId: "requestId" } };

        server.mockEndpoint().get("/v1/tools").respondWith().statusCode(429).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.metadata.listTools();
        }).rejects.toThrow(Alpha.TooManyRequestsError);
    });
});
