// This file was auto-generated by Fern from our API Definition.

import * as Alpha from "../../src/api/index";
import { AlphaClient } from "../../src/Client";
import { mockServerPool } from "../mock-server/MockServerPool";

describe("VaultsClient", () => {
    test("listVaults (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new AlphaClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { data: { key: "value" } };

        server.mockEndpoint().get("/v1/vaults").respondWith().statusCode(200).jsonBody(rawResponseBody).build();

        const response = await client.vaults.listVaults();
        expect(response).toEqual(rawResponseBody);
    });

    test("listVaults (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new AlphaClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "code", message: "message", requestId: "requestId" } };

        server.mockEndpoint().get("/v1/vaults").respondWith().statusCode(400).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.vaults.listVaults();
        }).rejects.toThrow(Alpha.BadRequestError);
    });

    test("listVaults (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new AlphaClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "code", message: "message", requestId: "requestId" } };

        server.mockEndpoint().get("/v1/vaults").respondWith().statusCode(401).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.vaults.listVaults();
        }).rejects.toThrow(Alpha.UnauthorizedError);
    });

    test("listVaults (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new AlphaClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "code", message: "message", requestId: "requestId" } };

        server.mockEndpoint().get("/v1/vaults").respondWith().statusCode(403).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.vaults.listVaults();
        }).rejects.toThrow(Alpha.ForbiddenError);
    });

    test("listVaults (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new AlphaClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "code", message: "message", requestId: "requestId" } };

        server.mockEndpoint().get("/v1/vaults").respondWith().statusCode(404).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.vaults.listVaults();
        }).rejects.toThrow(Alpha.NotFoundError);
    });

    test("listVaults (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new AlphaClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "code", message: "message", requestId: "requestId" } };

        server.mockEndpoint().get("/v1/vaults").respondWith().statusCode(429).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.vaults.listVaults();
        }).rejects.toThrow(Alpha.TooManyRequestsError);
    });
});
