// This file was auto-generated by Fern from our API Definition.

import { ActionsClient } from "./api/resources/actions/client/Client.js";
import { KnowledgeClient } from "./api/resources/knowledge/client/Client.js";
import { MetadataClient } from "./api/resources/metadata/client/Client.js";
import { VaultsClient } from "./api/resources/vaults/client/Client.js";
import type { BaseClientOptions, BaseRequestOptions } from "./BaseClient.js";
import { type NormalizedClientOptionsWithAuth, normalizeClientOptionsWithAuth } from "./BaseClient.js";
import * as core from "./core/index.js";

export declare namespace AlphaClient {
    export type Options = BaseClientOptions;

    export interface RequestOptions extends BaseRequestOptions {}
}

export class AlphaClient {
    protected readonly _options: NormalizedClientOptionsWithAuth<AlphaClient.Options>;
    protected _metadata: MetadataClient | undefined;
    protected _vaults: VaultsClient | undefined;
    protected _knowledge: KnowledgeClient | undefined;
    protected _actions: ActionsClient | undefined;

    constructor(options: AlphaClient.Options = {}) {
        this._options = normalizeClientOptionsWithAuth(options);
    }

    public get metadata(): MetadataClient {
        return (this._metadata ??= new MetadataClient(this._options));
    }

    public get vaults(): VaultsClient {
        return (this._vaults ??= new VaultsClient(this._options));
    }

    public get knowledge(): KnowledgeClient {
        return (this._knowledge ??= new KnowledgeClient(this._options));
    }

    public get actions(): ActionsClient {
        return (this._actions ??= new ActionsClient(this._options));
    }

    /**
     * Make a passthrough request using the SDK's configured auth, retry, logging, etc.
     * This is useful for making requests to endpoints not yet supported in the SDK.
     * The input can be a URL string, URL object, or Request object. Relative paths are resolved against the configured base URL.
     *
     * @param {Request | string | URL} input - The URL, path, or Request object.
     * @param {RequestInit} init - Standard fetch RequestInit options.
     * @param {core.PassthroughRequest.RequestOptions} requestOptions - Per-request overrides (timeout, retries, headers, abort signal).
     * @returns {Promise<Response>} A standard Response object.
     */
    public async fetch(
        input: Request | string | URL,
        init?: RequestInit,
        requestOptions?: core.PassthroughRequest.RequestOptions,
    ): Promise<Response> {
        return core.makePassthroughRequest(
            input,
            init,
            {
                baseUrl: this._options.baseUrl ?? this._options.environment,
                headers: this._options.headers,
                timeoutInSeconds: this._options.timeoutInSeconds,
                maxRetries: this._options.maxRetries,
                fetch: this._options.fetch,
                logging: this._options.logging,
                getAuthHeaders: async () => (await this._options.authProvider.getAuthRequest()).headers,
            },
            requestOptions,
        );
    }
}
