// This file was auto-generated by Fern from our API Definition.

export const AlphaEnvironment = {
    Production: "https://mcp.openantares.com",
} as const;

export type AlphaEnvironment = typeof AlphaEnvironment.Production;
